const test_length = 16;

export default [
    { //0
        question: '1. อารมณ์ซึมเศร้า (เศร้าใจ, สิ้นหวัง, หมดหนทาง, ไร้ค่า)',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มี", is_other: false },
            { id: 2, content: "1. จะบอกภาวะความรู้สึกนี้ ต่อเมื่อถามเท่านั้น", is_other: false },
            { id: 3, content: "2. บอกภาวะความรู้สึกนี้ออกมาเอง", is_other: false },
            { id: 4, content: "3. สื่อภาวะความรู้สึกนี้โดยภาษากาย ได้แก่ ทางการแสดงสีหน้า, ท่าทาง, น้ำเสียง และมักร้องไห้", is_other: false },
            { id: 5, content: "4. ผู้ป่วยบอกเพียงความรู้สึกนี้อย่างชัดเจน ทั้งการบอกออกมาเอง และภาษากาย", is_other: false },
        ],
        next_state: [
            "1",
            "1",
            "1",
            "1",
            "1",
        ],
        score: [
            "0",
            "1",
            "2",
            "3",
            "4",
        ],
        test_length: test_length,
        step_no: 0,
        is_show_content_choice: false,
    },
    { //1
        question: '2. ความรู้สึกผิด',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มี", is_other: false },
            { id: 2, content: "1. ติเตียนตนเอง รู้สึกตนเองทำให้ผู้อื่นเสียใจ", is_other: false },
            { id: 3, content: "2. รู้สึกผิด หรือครุ่นคิดถึงความผิดพลาดหรือการก่อกรรมในอดีต", is_other: false },
            { id: 4, content: "3. ความเจ็บป่วยในปัจจุบันเป็นการลงโทษ, มีอาการหลงผิดว่าตนผิด", is_other: false },
            { id: 5, content: "4. ได้ยินเสียงกล่าวโทษ หรือประนาม และ/หรือ เห็นภาพหลอนที่ข่มขู่คุมคาม", is_other: false },
        ],
        next_state: [
            "2",
            "2",
            "2",
            "2",
            "2",
        ],
        score: [
            "0",
            "1",
            "2",
            "3",
            "4",
        ],
        test_length: test_length,
        step_no: 1,
        is_show_content_choice: false,
    },
    { //2
        question: '3. การฆ่าตัวตาย',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มี", is_other: false },
            { id: 2, content: "1. รู้สึกชีวิตไร้ค่า", is_other: false },
            { id: 3, content: "2. คิดว่าตนเองน่าจะตาย หรือความคิดใด ๆ เกี่ยวกับการตายที่อาจเกิดขึ้นได้กับตนเอง", is_other: false },
            { id: 4, content: "3. มีความคิดหรือท่าทีจะฆ่าตัวตาย", is_other: false },
            { id: 5, content: "4. พยายามที่จะฆ่าตัวตาย (ความพยายามใดๆ ที่รุนแรง ให้คะแนน 4)", is_other: false },
        ],
        next_state: [
            "3",
            "3",
            "3",
            "3",
            "3",
        ],
        score: [
            "0",
            "1",
            "2",
            "3",
            "4",
        ],
        test_length: test_length,
        step_no: 2,
        is_show_content_choice: false,
    },
    { //3
        question: '4. การนอนไม่หลับในช่วงต้น',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มีปัญหาเข้านอนแล้วหลับยาก", is_other: false },
            { id: 2, content: "1. แจ้งว่านอนหลับยากบางครั้ง ได้แก่ นานกว่า 1/2 ชั่วโมง", is_other: false },
            { id: 3, content: "2. แจ้งว่านอนหลับยากทุกคืน", is_other: false },
        ],
        next_state: [
            "4",
            "4",
            "4",
        ],
        score: [
            "0",
            "1",
            "2",
        ],
        test_length: test_length,
        step_no: 3,
        is_show_content_choice: false,
    },
    { //4
        question: '5. การนอนไม่หลับ ในช่วงกลาง',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มีปัญหา", is_other: false },
            { id: 2, content: "1. ผู้ป่วยแจ้งว่ากระสับกระส่ายและนอนหลับไม่สนิทช่วงกลางคืน", is_other: false },
            { id: 3, content: "2. ตื่นกลางดึก หากมีลุกจากที่นอน ให้คะแนน 2 (ยกเว้นเพื่อปัสสาวะ)", is_other: false },
        ],
        next_state: [
            "5",
            "5",
            "5",
        ],
        score: [
            "0",
            "1",
            "2",
        ],
        test_length: test_length,
        step_no: 4,
        is_show_content_choice: false,
    },
    { //5
        question: '6. การตื่นนอนเช้ากว่าปกติ',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มีปัญหา", is_other: false },
            { id: 2, content: "1. ตื่นแต่เช้ามืด แต่นอนหลับต่อได้", is_other: false },
            { id: 3, content: "2. นอนต่อไม่หลับอีก หากลุกจากเตียงไปแล้ว", is_other: false },
        ],
        next_state: [
            "6",
            "6",
            "6",
        ],
        score: [
            "0",
            "1",
            "2",
        ],
        test_length: test_length,
        step_no: 5,
        is_show_content_choice: false,
    },
    { //6
        question: '7. การงานและกิจกรรม',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มีปัญหา", is_other: false },
            { id: 2, content: "1. มีความคิดและความรู้สึกว่าตนเองไม่มีสมรรถภาพ, อ่อนเปลี้ย, หรือหย่อนกำลังที่จะทำ กิจกรรมต่าง ๆ ; การงาน หรืองานอดิเรก", is_other: false },
            { id: 3, content: "2. หมดความสนใจในกิจกรรมต่างๆ ; งานอดิเรก หรืองานประจำ-ไม่ว่าจะทราบโดยตรงจาก การบอกเล่าของผู้ป่วย หรือทางอ้อมจากการไม่กระตือรือร้น, ลังเลใจ และเปลี่ยนใจไปมา (ผู้ป่วยรู้สึกว่าต้องกระตุ้นให้ตนเองทำงานหรือกิจกรรม)", is_other: false },
            { id: 4, content: "3. เวลาที่ใช้จริงในการทำกิจกรรมลดลง หรือผลงานลดลง หากอยู่ในโรงพยาบาล, ให้ คะแนน 3 ถ้าผู้ป่วยใช้เวลาต่ำกว่า 3 ชั่วโมงต่อวันในการทำกิจกรรม (งานของโรงพยาบาล หรืองานอดิเรก) ยกเว้นหน้าที่ประจำวันในโรงพยาบาล", is_other: false },
            { id: 5, content: "4. หยุดทำงานเพราะการเจ็บป่วยในปัจจุบัน. หากอยู่ในโรงพยาบาล, ให้คะแนน 4 ถ้าผู้ป่วย ไม่ทำกิจกรรมอื่นนอกจากหน้าที่ประจำวันในโรงพยาบาล หรือถ้าผู้ป่วยทำหน้าที่ประจำวัน ไม่ได้หากไม่มีคนช่วย", is_other: false },
        ],
        next_state: [
            "7",
            "7",
            "7",
            "7",
            "7",
        ],
        score: [
            "0",
            "1",
            "2",
            "3",
            "4",
        ],
        test_length: test_length,
        step_no: 6,
        is_show_content_choice: false,
    },
    { //7
        question: '8. อาการเชื่องช้า (ความช้าของความคิดและการพูดจา: สมาธิบกพร่อง, การเคลื่อนไหวลดลง)',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. การพูดจาและความคิดปกติ", is_other: false },
            { id: 2, content: "1. มีอาการเชื่องช้าเล็กน้อยขณะสัมภาษณ์", is_other: false },
            { id: 3, content: "2. มีอาการเชื่องช้าชัดเจนขณะสัมภาษณ์", is_other: false },
            { id: 4, content: "3. สัมภาษณ์ได้อย่างลำบาก", is_other: false },
            { id: 5, content: "4. อยู่นิ่งเฉยโดยสิ้นเชิง", is_other: false },
        ],
        next_state: [
            "8",
            "8",
            "8",
            "8",
            "8",
        ],
        score: [
            "0",
            "1",
            "2",
            "3",
            "4",
        ],
        test_length: test_length,
        step_no: 7,
        is_show_content_choice: false,
    },
    { //8
        question: '9. อาการกระวนกระวายทั้งกายและใจ',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มี", is_other: false },
            { id: 2, content: "1. งุ่นง่าน อยู่ไม่สุข", is_other: false },
            { id: 3, content: "2. เล่นมือ เล่นผม ฯลฯ", is_other: false },
            { id: 4, content: "3. เดินไปมา นั่งไม่ติดที่", is_other: false },
            { id: 5, content: "4. บีบมือ กัดเล็บ ดึงผม กัดริมฝีปาก", is_other: false },
        ],
        next_state: [
            "9",
            "9",
            "9",
            "9",
            "9",
        ],
        score: [
            "0",
            "1",
            "2",
            "3",
            "4",
        ],
        test_length: test_length,
        step_no: 8,
        is_show_content_choice: false,
    },
    { //9
        question: '10. ความวิตกกังวลในจิตใจ',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มีปัญหา", is_other: false },
            { id: 2, content: "1. รู้สึกตึงเครียด และหงุดหงิด", is_other: false },
            { id: 3, content: "2. กังวลในเรื่องเล็กน้อย", is_other: false },
            { id: 4, content: "3. การพูดจาหรือสีหน้ามีท่าทีหวั่นกลัว", is_other: false },
            { id: 5, content: "4. แสดงความหวาดกลัว โดยไม่ต้องถาม", is_other: false },
        ],
        next_state: [
            "10",
            "10",
            "10",
            "10",
            "10",
        ],
        score: [
            "0",
            "1",
            "2",
            "3",
            "4",
        ],
        test_length: test_length,
        step_no: 9,
        is_show_content_choice: false,
    },
    { //10
        question: '11. ความวิตกกังวลซึ่งแสดงออกทางกาย',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มี", is_other: false },
            { id: 2, content: "1. เล็กน้อย", is_other: false },
            { id: 3, content: "2. ปานกลาง", is_other: false },
            { id: 4, content: "3. รุนแรง", is_other: false },
            { id: 5, content: "4. เสื่อมสมรรถภาพ", is_other: false },
        ],
        next_state: [
            "11",
            "11",
            "11",
            "11",
            "11",
        ],
        score: [
            "0",
            "1",
            "2",
            "3",
            "4",
        ],
        remark: 'อาการร่วมด้านสรีระวิทยาของความวิตกกังวล เช่น\n-ระบบทางเดินอาหาร: ปากแห้ง ลมขึ้น อาหารไม่ย่อย ท้องเสีย ปวดเกร็งท้อง เรอ\n-ระบบหัวใจและหลอดเลือด: ใจสั่น ปวดศีรษะ\n-ระบบหายใจ: หายใจหอบเร็ว ถอนหายใจ\n-ปัสสาวะบ่อย\n-เหงื่อออก',
        test_length: test_length,
        step_no: 10,
        is_show_content_choice: true,
    },
    { //11
        question: '12. อาการทางกาย ระบบทางเดินอาหาร',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มี", is_other: false },
            { id: 2, content: "1. เบื่ออาหาร แต่รับประทานโดยผู้อื่นไม่ต้องคอยกระตุ้น\n- รู้สึกหน่วงในท้อง", is_other: false },
            { id: 3, content: "2. รับประทานยากหากไม่มีคนคอยกระตุ้น\n- ขอหรือจำต้องได้ยาระบายหรือยาเกี่ยวกับลำไส้ หรือยาสำหรับอาการของระบบ ทางเดินอาหาร", is_other: false },
        ],
        next_state: [
            "12",
            "12",
            "12",
        ],
        score: [
            "0",
            "1",
            "2",
        ],
        test_length: test_length,
        step_no: 11,
        is_show_content_choice: false,
    },
    { //12
        question: '13. อาการทางกาย อาการทั่วไป',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มี", is_other: false },
            { id: 2, content: "1. ตึงแขนขา หลังหรือศีรษะ ปวดหลัง ปวดศีรษะ ปวดกล้ามเนื้อ หมดแรงและอ่อนเพลีย", is_other: false },
            { id: 3, content: "2. มีอาการใด ๆ ที่ชัดเจน", is_other: false },
        ],
        next_state: [
            "13",
            "13",
            "13",
        ],
        score: [
            "0",
            "1",
            "2",
        ],
        test_length: test_length,
        step_no: 12,
        is_show_content_choice: false,
    },
    { //13
        question: '14. อาการทางระบบสืบพันธุ์',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มี อาการเช่น : หมดความต้องการทางเพศ, ปัญหาด้านประจำเดือน", is_other: false },
            { id: 2, content: "1. เล็กน้อย", is_other: false },
            { id: 3, content: "2. ปานกลาง", is_other: false },
        ],
        next_state: [
            "14",
            "14",
            "14",
        ],
        score: [
            "0",
            "1",
            "2",
        ],
        test_length: test_length,
        step_no: 13,
        is_show_content_choice: false,
    },
    { //14
        question: '15. อาการคิดว่าตนป่วยเป็นโรคทางกาย',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ไม่มี", is_other: false },
            { id: 2, content: "1. หมกมุ่นในตนเอง (ด้านร่างกาย)", is_other: false },
            { id: 3, content: "2. หมกมุ่นเรื่องสุขภาพ", is_other: false },
            { id: 4, content: "3. แจ้งถึงอาการต่าง ๆ บ่อย เรียกร้องความช่วยเหลือ ฯลฯ", is_other: false },
            { id: 5, content: "4. มีอาการหลงผิดว่าตนป่วยเป็นโรคทางกาย", is_other: false },
        ],
        next_state: [
            "15",
            "15",
            "15",
            "15",
            "15",
        ],
        score: [
            "0",
            "1",
            "2",
            "3",
            "4",
        ],
        test_length: test_length,
        step_no: 14,
        is_show_content_choice: false,
    },
    { //15
        question: '16. น้ำหนักลด เลือกตอบข้อ ก หรือ ข ข้อใดข้อหนึ่ง',
        answer_type: 'option_selection',
        choices: [
            {
                id: 1, content: "ก. เมื่อให้คะแนนโดยอาศัยประวัติ", is_other: false, is_selection: true,
                sub_choices: [
                    { id: 1, content: "0. ไม่มีน้ำหนักลด", is_other: false },
                    { id: 2, content: "1. อาจมีน้ำหนักลด ซึ่งเกี่ยวเนื่องกับการเจ็บป่วยครั้งนี้", is_other: false },
                    { id: 3, content: "2. น้ำหนักลดชัดเจน (ตามที่ผู้ป่วยบอก)", is_other: false },
                    { id: 4, content: "3. ไม่ได้ประเมิน", is_other: false },
                ]
            },
            {
                id: 2, content: "ข. จากการให้คะแนนประจำสัปดาห์โดยจิตแพทย์ประจำหอผู้ป่วย เมื่อชั่งวัดน้ำหนักที่เปลี่ยนไปจริง", is_other: false, is_selection: true,
                sub_choices: [
                    { id: 5, content: "0. น้ำหนักลดน้อยกว่า 0.5 กิโลกรัม ใน 1 สัปดาห์", is_other: false },
                    { id: 6, content: "1. น้ำหนักลดมากกว่า 0.5 กิโลกรัม ใน 1 สัปดาห์", is_other: false },
                    { id: 7, content: "2. น้ำหนักลดมากกว่า 1 กิโลกรัม ใน 1 สัปดาห์", is_other: false },
                    { id: 8, content: "3. ไม่ได้ประเมิน", is_other: false },
                ]
            },
        ],
        next_state: [
            "16",
            "16",
            "16",
            "16",
            "16",
            "16",
            "16",
            "16",
        ],
        score: [
            "0",
            "1",
            "2",
            "3",
            "0",
            "1",
            "2",
            "3",
        ],
        test_length: test_length,
        step_no: 15,
        branch_node_level: 1,
        is_show_content_choice: false,
    },
    { //16
        question: '17. การหยั่งเห็นถึงความผิดปกติของตนเอง',
        answer_type: 'option',
        choices: [
            { id: 1, content: "0. ยอมรับว่ากำลังซึมเศร้า และเจ็บป่วย", is_other: false },
            { id: 2, content: "1. ยอมรับความเจ็บป่วย แต่โยงสาเหตุกับ อาหารที่เลว ดินฟ้าอากาศ, การทำงานหนัก ไวรัส การต้องการพักผ่อน ฯลฯ", is_other: false },
            { id: 3, content: "2. ปฏิเสธการเจ็บป่วยโดยสิ้นเชิง", is_other: false },
        ],
        next_state: [
            "0",
            "0",
            "0",
        ],
        score: [
            "0",
            "1",
            "2",
        ],
        test_length: test_length,
        step_no: 16,
        is_show_content_choice: false,
    },
]